# Generated by Django 4.1.7 on 2023-03-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="confession_comment",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
