# Generated by Django 4.1.4 on 2022-12-29 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_comment_created_at_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likeOrDislike',
            field=models.CharField(choices=[('Like', 'LIKE'), ('Dislike', 'DISLIKE')], default='Dislike', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
