# Generated by Django 4.1.4 on 2022-12-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_likeordislike_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likeOrDislike',
        ),
        migrations.AddField(
            model_name='comment',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
