# Generated by Django 4.1.4 on 2022-12-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=80)),
                ('college', models.CharField(choices=[('Universidad de Puerto Rico, Rio Piedras', 'UPRRP'), ('Universidad de Puerto Rico, Mayaguez', 'UPRM')], max_length=100)),
                ('faculty', models.CharField(choices=[('Naturales', 'Naturales'), ('Humanidades', 'Humanidades')], max_length=30)),
                ('average_difficulty', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1)),
                ('average_grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1)),
                ('pro_student', models.BooleanField()),
                ('organized', models.BooleanField()),
            ],
        ),
    ]
