# Generated by Django 4.1.6 on 2023-02-21 05:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="pro_student",
            new_name="recommended",
        ),
    ]
