# Generated by Django 4.1.6 on 2023-02-19 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="codification",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(8),
                    django.core.validators.MaxLengthValidator(8),
                ],
            ),
        ),
    ]
