from django.core.management.base import BaseCommand
from faker import Faker
import random

from courses.models import Course
from professors.models import Professor


class Command(BaseCommand):
    help = "Populates the database with courses"

    def handle(self, *args, **options):
        professors = Professor.objects.all()
        fake = Faker()
        codifications = [
            "BIOL",
            "CHEM",
            "MATH",
            "PHYS",
            "STAT",
            "COMP",
            "ECON",
            "ENGL",
            "HIST",
            "PHIL",
            "PSYC",
            "ANTH",
            "ARCH",
            "ART",
            "COMM",
            "DANC",
            "FILM",
            "MUSC",
            "THEA",
            "AFAM",
            "ASAM",
            "CHST",
            "LATN",
            "LING",
            "LITR",
            "SPAN",
            "WGST",
            "AFST",
            "ANTH",
            "ECON",
            "GEOG",
            "HIST",
            "POLI",
            "PSYC",
            "SOCI",
            "URBS",
            "BIOL",
            "CHEM",
            "MATH",
            "PHYS",
            "STAT",
            "COMP",
            "ECON",
            "ENGL",
            "HIST",
            "PHIL",
            "PSYC",
            "ANTH",
            "ARCH",
            "ART",
            "COMM",
            "DANC",
            "FILM",
            "MUSC",
            "THEA",
            "AFAM",
            "ASAM",
            "CHST",
            "LATN",
            "LING",
            "LITR",
            "SPAN",
            "WGST",
            "AFST",
            "ANTH",
            "ECON",
            "GEOG",
            "HIST",
            "POLI",
            "PSYC",
            "SOCI",
            "URBS",
            "BIOL",
            "CHEM",
            "MATH",
            "PHYS",
            "STAT",
            "COMP",
            "ECON",
            "ENGL",
            "HIST",
            "PHIL",
            "PSYC",
            "ANTH",
            "ARCH",
            "ART",
            "COMM",
            "DANC",
            "FILM",
            "MUSC",
            "THEA",
            "AFAM",
            "ASAM",
            "CHST",
            "LATN",
            "LING",
            "LITR",
            "SPAN",
            "WGST",
            "AFST",
            "ANTH",
            "ECON",
            "GEOG",
            "HIST",
            "POLI",
            "PSYC",
            "SOCI",
            "URBS",
            "BIOL",
            "CHEM",
            "MATH",
            "PHYS",
            "STAT",
            "COMP",
            "ECON",
            "ENGL",
            "HIST",
            "PHIL",
            "PSYC",
            "ANTH",
            "ARCH",
            "ART",
            "COMM",
            "DANC",
            "FILM",
            "MUSC",
            "THEA",
            "AFAM",
            "ASAM",
            "CHST",
            "LATN",
            "LING",
            "LITR",
            "SPAN",
            "WGST",
            "AFST",
        ]
        for professor in professors:
            for i in range(random.randint(3, 8)):
                numbers = random.randint(1000, 9999)
                Course.objects.create(
                    name=fake.sentence(nb_words=6, variable_nb_words=True),
                    codification=random.choice(codifications) + str(numbers),
                    professor=professor,
                )
        self.stdout.write(self.style.SUCCESS("Successfully populated courses!"))
