# Generated by Django 4.1.6 on 2023-02-25 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("confessions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="confession",
            name="downvotes",
        ),
        migrations.RemoveField(
            model_name="confession",
            name="upvotes",
        ),
        migrations.AddField(
            model_name="confession",
            name="downvotes",
            field=models.ManyToManyField(
                related_name="confession_downvotes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="confession",
            name="upvotes",
            field=models.ManyToManyField(
                related_name="confession_upvotes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
