# Generated by Django 4.1.6 on 2023-02-27 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("professors", "0002_college_department_alter_professor_college_and_more"),
        ("confessions", "0002_remove_confession_downvotes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="confession",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="confession",
            name="college",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="professors.college",
            ),
        ),
    ]
